Repository slack-samples/bolt-js-assistant-template, pull requests merged in 2025-10, with the labels that each got.

#73 feat: feedback button
  app.js
Labels: enhancement

#74 refactor: organize app into the common template directory structure
  ai/index.js
  app.js
  listeners/actions/feedback.js
  listeners/actions/index.js
  listeners/assistant/assistant_thread_context_changed.js
  listeners/assistant/assistant_thread_started.js
  listeners/assistant/index.js
  listeners/assistant/message.js
  listeners/events/app_mention.js
  listeners/events/index.js
  listeners/index.js
  listeners/views/feedback_block.js
  package.json
Labels: update

#77 feat: add ai-enabled features text streaming, loading states, and feedback buttons
  .env.sample
  README.md
  ai/index.js
  app.js
  listeners/actions/feedback.js
  listeners/actions/index.js
  listeners/assistant/assistant_thread_context_changed.js
  listeners/assistant/assistant_thread_started.js
  listeners/assistant/index.js
  listeners/assistant/message.js
  listeners/events/app_mention.js
  listeners/events/index.js
  listeners/index.js
  listeners/views/feedback_block.js
  manifest.json
  package-lock.json
  package.json
Labels: enhancement, update

#78 fix: reorder dotenv imports in app.js to load .env file properly
  app.js
Labels: bug
